# Public-Dataset-AG
#
# VERSION	1.0

#   Copyright 2016 The Trustees of University of Arizona
#
#   Licensed under the Apache License, Version 2.0 (the "License" );
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.



FROM	ubuntu:14.04
MAINTAINER	Illyoung Choi <iychoi@email.arizona.edu>

##############################################
# Setup environment
##############################################
ENV LD_LIBRARY_PATH /usr/local/lib

##############################################
# Setup a Syndicate account
##############################################
ENV USER syndicate
ENV HOME /home/$USER

RUN useradd $USER && echo 'syndicate:syndicate' | chpasswd && \
    echo "syndicate ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir /home/$USER && \
    chown -R $USER:$USER $HOME

WORKDIR $HOME

##############################################
# Setup Syndicate
##############################################
ENV APT_KEY butler_opencloud_cs_arizona_edu_pub.gpg

# Prep apt to be able to download over https
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --allow-unauthenticated --no-install-recommends \
    apt-transport-https ca-certificates fuse \
    wget curl unzip python-pip build-essential ssh && \
    apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt /var/lib/cache /var/lib/log && \
    groupadd -f fuse && \
    usermod -aG fuse $USER

# Copy over and trust https cert
COPY butler.crt /usr/local/share/ca-certificates
COPY $APT_KEY /tmp/

RUN update-ca-certificates && \
    apt-key add /tmp/$APT_KEY && \
    echo "deb https://butler.opencloud.cs.arizona.edu/repos/release/syndicate syndicate main" > /etc/apt/sources.list.d/butler.list


##############################################
# fskit
##############################################
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --allow-unauthenticated --no-install-recommends \
    libfuse-dev libattr1-dev && \
    apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt /var/lib/cache /var/lib/log

USER $USER
RUN wget -O fskit.zip https://github.com/iychoi/fskit/archive/master.zip && \
    unzip fskit.zip && mv fskit-master fskit
WORKDIR "fskit"
RUN make

USER root
RUN make install && ldconfig

WORKDIR $HOME


##############################################
# syndicate
##############################################
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --allow-unauthenticated --no-install-recommends \
    protobuf-compiler libprotobuf-dev libgnutls-dev libjson0-dev valgrind \
    cython python-protobuf libssl-dev libgcrypt11-dev libcurl4-gnutls-dev \
    libevent-dev python-crypto python-requests python-dev libffi-dev && \
    apt-get clean autoclean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt /var/lib/cache /var/lib/log && \
    pip install -v greenlet gevent==1.2.2 grequests

###### libmicrohttpd (0.9.44)
RUN wget https://butler.opencloud.cs.arizona.edu/stopgap/libmicrohttpd-dbg_0.9.44+dfsg-1ubuntu2_amd64.deb && \
    wget https://butler.opencloud.cs.arizona.edu/stopgap/libmicrohttpd-dev_0.9.44+dfsg-1ubuntu2_amd64.deb && \
    wget https://butler.opencloud.cs.arizona.edu/stopgap/libmicrohttpd10_0.9.44+dfsg-1ubuntu2_amd64.deb && \
    dpkg -i libmicrohttpd-dbg_0.9.44+dfsg-1ubuntu2_amd64.deb libmicrohttpd-dev_0.9.44+dfsg-1ubuntu2_amd64.deb libmicrohttpd10_0.9.44+dfsg-1ubuntu2_amd64.deb && \
    apt-get -f install && \
    rm libmicrohttpd-dbg_0.9.44+dfsg-1ubuntu2_amd64.deb libmicrohttpd-dev_0.9.44+dfsg-1ubuntu2_amd64.deb libmicrohttpd10_0.9.44+dfsg-1ubuntu2_amd64.deb

USER $USER
WORKDIR $HOME

###### syndicate-core
RUN wget -O syndicate-core.zip https://github.com/iychoi/syndicate-core/archive/master.zip && \
    unzip syndicate-core.zip && mv syndicate-core-master syndicate-core
WORKDIR "syndicate-core"

RUN make MS_APP_ADMIN_EMAIL="iychoi@email.arizona.edu" MS_APP_PUBLIC_HOST="localhost"

USER root
RUN make install && ldconfig

USER $USER
WORKDIR $HOME


##############################################
# syndicate AG
##############################################
RUN wget -O syndicate-ag.zip https://github.com/iychoi/syndicate-ag/archive/master.zip && \
    unzip syndicate-ag.zip && mv syndicate-ag-master syndicate-ag
WORKDIR "syndicate-ag"

RUN make

USER root
RUN make install && ldconfig

WORKDIR $HOME

###### syndicate-fs-driver dependencies
USER root
RUN pip install pika pyinotify expiringdict boto3 ftputil

USER $USER

# install python-irodsclient from github
RUN wget -O python-irodsclient.zip https://github.com/iychoi/python-irodsclient/archive/master.zip && \
    unzip python-irodsclient.zip && mv python-irodsclient-master python-irodsclient
WORKDIR "python-irodsclient"

USER root
RUN python setup.py install

WORKDIR $HOME
USER $USER

###### syndicate-filesystem-driver
RUN wget -O syndicate-fs-driver.zip https://github.com/syndicate-storage/syndicate-fs-driver/archive/master.zip && \
    unzip syndicate-fs-driver.zip && mv syndicate-fs-driver-master syndicate-fs-driver
WORKDIR "syndicate-fs-driver"

USER root
# need to ignore warnings (setuptools is too old)
RUN python -W ignore setup.py install

WORKDIR $HOME


##############################################
# scripts
##############################################
COPY init_container.sh /usr/bin/
COPY start_ag.sh /usr/bin/
COPY manipulate_ag_config.py /usr/bin/

RUN chmod 777 /usr/bin/init_container.sh && \
    chmod 777 /usr/bin/start_ag.sh && \
    chmod 777 /usr/bin/manipulate_ag_config.py

USER $USER

CMD bash -C '/usr/bin/init_container.sh'
