# docker-compose.yml for demo-cyverse-ag

version: '2'

services:
  appspot_production_imicrobe:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh syndicate-ms-datasets.appspot.com:80 cyverse@opencloud.us imicrobe ag_imicrobe demo2.opencloud.cs.arizona.edu:31521 imicrobe_anonymous
    ports:
      - "31521:31521"
    volumes:
      - ../imicrobe/private:/opt/private:rw
      - ../imicrobe/driver:/opt/driver:rw

  appspot_production_ivirus:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh syndicate-ms-datasets.appspot.com:80 cyverse@opencloud.us ivirus ag_ivirus demo2.opencloud.cs.arizona.edu:31522 ivirus_anonymous
    ports:
      - "31522:31522"
    volumes:
      - ../ivirus/private:/opt/private:rw
      - ../ivirus/driver:/opt/driver:rw

  appspot_production_digbio:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh syndicate-ms-datasets.appspot.com:80 cyverse@opencloud.us digbio ag_digbio demo2.opencloud.cs.arizona.edu:31523 digbio_anonymous
    ports:
      - "31523:31523"
    volumes:
      - ../digbio/private:/opt/private:rw
      - ../digbio/driver:/opt/driver:rw

  appspot_production_panzea:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh syndicate-ms-datasets.appspot.com:80 cyverse@opencloud.us panzea ag_panzea demo2.opencloud.cs.arizona.edu:31524 panzea_anonymous
    ports:
      - "31524:31524"
    volumes:
      - ../panzea/private:/opt/private:rw
      - ../panzea/driver:/opt/driver:rw

  appspot_production_pov:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh syndicate-ms-datasets.appspot.com:80 cyverse@opencloud.us pov ag_pov demo2.opencloud.cs.arizona.edu:31525 pov_anonymous
    ports:
      - "31525:31525"
    volumes:
      - ../pov/private:/opt/private:rw
      - ../pov/driver:/opt/driver:rw

  appspot_demo_imicrobe:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh syndicate-ms-demo.appspot.com:80 cyverse@opencloud.us imicrobe ag_imicrobe demo2.opencloud.cs.arizona.edu:31531 imicrobe_anonymous
    ports:
      - "31531:31531"
    volumes:
      - ../imicrobe/private:/opt/private:rw
      - ../imicrobe/driver:/opt/driver:rw
