# docker-compose.yml for demo-cyverse-ag

version: '2'

services:
  ag_pov:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh ag_pov cyverse@cyverse.org pov
    ports:
      - "31111:31111"
    volumes:
      - ../privates/ag_pov:/home/syndicate/syndicate_in
      - ../drivers/ag_pov:/home/syndicate/driver_in
