# docker-compose.yml for demo-cyverse-ag

version: '2'

services:
  ag01:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh AG01 iychoi@email.arizona.edu test-volume
    ports:
      - "31111:31111"
    volumes:
      - ../privates/ag01:/home/syndicate/.syndicate
      - ../drivers/ag01:/home/syndicate/driver
