# docker-compose.yml for demo-cyverse-ag

version: '2'

services:
  ag_pov:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh ag_pov cyverse@cyverse.org pov demo1.opencloud.cs.arizona.edu 28080 31111
    ports:
      - "31111:31111"
    volumes:
      - ../ag_pov/private:/opt/private:rw
      - ../ag_pov/driver:/opt/driver:rw
