# docker-compose.yml for demo-cyverse-ag

version: '2'

services:
  appspot_demo_imicrobe:
    extends:
      file: docker-compose-base.yml
      service: ag_base
    entrypoint: start_gateway.sh https://syndicate-ms-demo.appspot.com:80 cyverse@opencloud.us imicrobe ag_imicrobe demo2.opencloud.cs.arizona.edu:31521 imicrobe_anonymous
    ports:
      - "31521:31521"
    volumes:
      - ../imicrobe/private:/opt/private:rw
      - ../imicrobe/driver:/opt/driver:rw
